<?php
if (!defined('SMF'))
	die('Hacking attempt...');
	
//SMFPredictionLeague Admin Language File
//SMFPredictionLeagueAdmin.english.php

$txt['SMFPredictionLeague_admin'] = 'Prediction League Admin';

$txt['SMFPredictionLeagueAdmin_Pms'] = array(
	'fixtures_entered_title' => 'Prediction League Fixtures Entered',
	'results_entered_title' => 'Prediction League Results Entered',
	'fixtures_entered_body' => '[i][size=1]Note that this PM is autogenerated[/size][/i]

New fixtures have been entered into the Prediction League. Dont forget to enter your predictions for these fixtures. You can go to the Prediction League by clicking the URL below. You may turn off these automatic PMs within you User Profile area inside the Prediction League.

Good luck!',
	'results_entered_body' => '[i][size=1]Note that this PM is autogenerated[/size][/i]

Results have been entered in the Prediction League. Go and check whether your position has changed. You can go to the Prediction League by clicking the URL below. You may turn off these automatic PMs within you User Profile area inside the Prediction League.

Good luck!',
);

// Text for any titles that appear in the admin section
$txt['SMFPredictionLeagueAdmin_Titles'] = array(
	'title_settings' => 'Settings',
	'title_fixtures' => 'Fixtures',
	'title_results' => 'Results',
	'title_teams' => 'Teams',
	'title_support' => 'Support',
	'title_maintenance' => 'Maintenance',
	'title_admin' => 'Prediction League Admin',
);

// Text for any blurb that is associated with titles that appear in the admin section
$txt['SMFPredictionLeague_TitlesBlurb'] = array(
	'title_settings_blurb' => 'This page allows you to change the general settings of the Prediction League',
	'title_fixtures_blurb' => 'This page allows you to enter and modify fixtures in the Prediction League',
	'title_results_blurb' => 'This page allows you to enter outstanding results or modify results that were previously entered into the Prediction League',
	'title_teams_blurb' => 'This page alloows you to manage the team data',
	'title_support_blurb' => 'This page allows you to view support information for the mod and get latest news',
);

// Text for status update text that appears in the admin section
$txt['SMFPredictionLeague_StatusUpdateText'] = array(
	'weekIncremented' => 'Week Incremented',
	'updatesSaved' => 'Updates Saved',
	'fixturesSaved' => 'Fixtures Saved',
	'fixturesDeleted' => 'Fixtures Deleted',
	'resultsSaved' => 'Results Saved',
	'add_teams' => 'Teams Added',
);

// Text for any headings that appear in the admin section
$txt['SMFPredictionLeagueAdmin_Headings'] = array(
	'drawsEnabled' => 'Draws Enabled',
	'maximumPredictionScore' => 'Maximum Prediction Score',
	'timeOffset' => 'Time Offest',
	'serverTime' => 'Current Server Time',
	'serverTimeAndOffset' => 'Time with Offset',
	'offsetMessage' => 'This should match the time where the fixtures are played',
	'resultsForWeek' => 'Entered Results for week',
	'fixturesForWeek' => 'Entered Fixtures for week',
	'generalSettings' => 'General Settings',
	'predictionLeagueEnabled' => 'Prediction League Enabled',
	'adminDebugEnabled' => 'Admin Debug Enabled',
	'pmsEnabled' => 'Auto PMs Enabled',
	'usersPerPage' => 'Users per Page',
	'pointsForHomeScore' => 'Points for Home Score',
	'pointsForAwayScore' => 'Points for Away Score',
	'pointsForCorrectResult' => 'Points for Correct Result',
	'pointsForCorrectScore' => 'Points for Correct Score',
	'firstPlaceBackground' => '1st Place Background',
	'secondPlaceBackground' => '2nd Place Background',
	'thirdPlaceBackground' => '3rd Place Background',
	'multipleFixturesForWeek' => 'Enter Multiple Fixtures for week',
	'outstandingResults' => 'Outstanding Results',
	'noOutstandingResults' => 'There are no outstanding results',
	'noFixtures' => 'No fixtures have been entered for this week, so no results are available to add',
	'noFixturesForWeek' => 'No fixtures have been entered for this week',
	'databaseMaintenance' => 'Database Maintenance Activities',
);

// Text for any column headings that appear in the admin section
$txt['SMFPredictionLeagueAdmin_ColumnHeadings'] = array(
	'date' => 'Date',
	'home' => 'Home Team',
	'away' => 'Away Team',
	'time' => 'Time',
	'teamName' => 'Team Name',
	'image' => 'Image Filename',
	'match' => 'Match',
	'dateWithFormat' => 'Date (YYYY-MM-DD)',
	'timeWithFormat' => 'Time (HH:MM)',
);

// Text for any buttons that appear in the admin section
$txt['SMFPredictionLeagueAdmin_Buttons'] = array(
	'saveResults' => 'Save Results',
	'outstandingResults' => 'Outstanding Results',
	'saveUpdates' => 'Save Updates',
	'save' => 'Save',
	'addTeam' => 'Add Team',
	'removeSelectedTeams' => 'Remove Selected Teams',
);

// Text for error messages in admin section
$txt['SMFPredictionLeague_errors'] = array(	
	'noweeks' => 'No week number exists within the database, this means it hasnt been setup correctly. Please review the table smf_pl_week if you think this is an error. If this is the first time you have entered the Prediction League you can generate this now by clicking the button below.',
	'nofixtures' => 'No fixtures have been entered into the database yet for the selected week',
	'noTeams' => 'No teams have been entered into the database yet',
);

// Text for any help in admin section
$txt['SMFPredictionLeague_help'] = array(
	'drawsEnabledHelp' => 'Not all sports have the concept of draws. Untick this box if your sport does not have draws',
	'maximumPredictionScore' => 'The maximum score the user can select from the dropdown when predicting',
	'enabledHelp' => 'Whether the Prediction League is on or off',
	'adminDebugOnHelp' => 'This will turn on the custom debugging option available for admin users to see only',
	'pmsOnHelp' => 'If this is ticked then PMs will be automatically sent when entering results and fixtures to those members that have enabled the option (unless overridden in the admin). Disabling this will mean no PMs are sent during admin at all.',
	'timeOffsetHelp' => 'This is the time offset (in hours) you want to set against the servers time in order to make sure the match times are correct',
	'usersPerPageHelp' => 'How many users to show per page such as on the league table',
	'homeScorePointsHelp' => 'The number of points awarded for predicting the correct score for the home team',
	'awayScorePointsHelp' => 'The number of points awarded for predicting the correct score for the away team',
	'correctResultPointsHelp' => 'The number of points awarded for predicting the correct result type i.e. a win, a draw, a loss',
	'correctScorePointsHelp' => 'The number of points awarded for predicting the correct score for the match',
	'firstBackgroundHelp' => 'The background colour used for displaying first place users and excellent prediction results',
	'secondBackgroundHelp' => 'The background colour used for displaying second place users and good prediction results',
	'thirdBackgroundHelp' => 'The background colour used for displaying third place users and scoring prediction results',
);

// Misc text in admin section
$txt['SMFPredictionLeague_misc'] = array(	
	'debugTitle' => 'Prediction League Debugging Information',
	'debugBlurb' => 'Note that this box is shown only to administrators and is turned on because you have enabled it in the Prediction League settings section',
	'adminBlurb' => 'Edit the Prediction League settings in this section. Note that you must also grant permissions to the Prediction League in the General Permissions section of the SMF Administration center',
	'shoutboxCleanComplete' => 'Shoutbox has been cleaned',
	'wipeLeagueComplete' => 'Prediction League has been wiped',
);

?>

